[phases.setup]
# Use the Node.js runtime from nixpkgs instead of installing bun.
# This avoids pulling many extra packages at build time and matches
# this repo's `package.json` scripts which use `next`/npm.
nixPkgs = ["nodejs"]
aptPkgs = []

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
